hash-format = "sha256"

[[files]]
file = "datapacks/incendium.pw.toml"
hash = "316451db132efc659119de2e9243876e5bb0b5af5e046248f946958dbf87cf2c"
metafile = true

[[files]]
file = "datapacks/nullscape.pw.toml"
hash = "336ad19beaf2e7d1420a0e97f3a53a087851dbb58d328e8c4a49c227bc4d3be7"
metafile = true

[[files]]
file = "datapacks/terralith.pw.toml"
hash = "4c24b5e20f6a1718822c1541029349b03ac72bfcd0ee8e5a6b42775bf8c80f09"
metafile = true

[[files]]
file = "datapacks/trek.pw.toml"
hash = "5510c7572f01e43bb458171c7677b272773bc18a58ce660bb1a7a2304db7c566"
metafile = true

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "fa40e7c9879f4ad59dc466dca96e1f450395568d27c6a6f626047cefda8eaea9"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2e6a2f8c477128a76ef059dfef7ca8a1befa2ae0ebe7ae2171e716f0c905cd00"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "e154b918a8b473942f6428fb8f778c08b46befc2f55387dce75ca39164b83b00"
metafile = true

[[files]]
file = "mods/create-diesel-generators.pw.toml"
hash = "02fab017c89f55b1cfbde17d4c9c7945cbd6cac109cc0690a8dda5e4b6ccf44f"
metafile = true

[[files]]
file = "mods/create-dreams-desires.pw.toml"
hash = "25e8878491660347594ab7dc91f3075dcde12f5a20e84952a7a694ac78e4b758"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "6a7211cf26561896b195d7890867e25c1079a8717af6b675a68e14ed46b735b0"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "36effdfa56cf8aa6d563db77c5dd80b626693d0c77d0b4e3c244aa80c10cab05"
metafile = true

[[files]]
file = "mods/data-anchor.pw.toml"
hash = "7f02ff265c96a103bd044602ab48788520d364c22824a69a77da6f81dd984103"
metafile = true

[[files]]
file = "mods/enhanced-celestials.pw.toml"
hash = "0bb3a092472cc820e42e83ac0aac97e52f8cb2920777b79788bb04dc1da0cebc"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "875e9067e6b573d857ea6524cbf7c9bcaa7a4fc129fe18b422dab88692ddbbaa"
metafile = true

[[files]]
file = "mods/guard-villagers.pw.toml"
hash = "7db4d6f071da73553f0a3d4ca115c89a24effb6c87e15d8f7cebc464239a89c8"
metafile = true

[[files]]
file = "mods/improved-mobs.pw.toml"
hash = "748fda6e06280872a42259eea26312a65d65aa6554d917f44a3658854bda5d39"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "ae86ce95fd8c6d3ff9b924b49beb7a272390ede057348645e6abef726473029e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "e8b121e7dd0d0dc6bee6a968e26c4c2f3cc2372157722bbdced899c62d372860"
metafile = true

[[files]]
file = "mods/prometheus-exporter.pw.toml"
hash = "95b1de582ae2ce9d6e534ea9789ef7915a164648efcd788564aa6609e8deb531"
metafile = true

[[files]]
file = "mods/saturn.pw.toml"
hash = "ddc79fcde38a25173360d928ed69b5cc357aa10b010fc37e0429c426b28d9fcc"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-create-integration.pw.toml"
hash = "df99ef6ffac5c9e897cb39a9cd8549159e43025e01c9168e1ec419bbca695384"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "6b971f27a8ae1ea033d81ebb6369ac2a586f5a80182913f3061a325b077f27ed"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "d145bcd9df3aedbcf414c44b9efde5bd9541ab2316b698bc6d8f1ca3160e9b97"
metafile = true

[[files]]
file = "mods/sophisticated-storage-create-integration.pw.toml"
hash = "0dd277e6d350ac314ed117f1c8cc997da0c2bb05c90ff1c024afc57c515ad948"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "9961f9bd1472ace0c1555ae5669cb4626849028b76d8e4bf065da2f6604830d4"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "11c3d2f6e23cce91ba2b2f1dffc700e9d0e6c8f7406f25bc3b04c93b5bc91b4b"
metafile = true

[[files]]
file = "mods/tenshilib.pw.toml"
hash = "41b9eccff7a35a85444c3aad9a998353c5f720086f43e8c36dc2d3b4a9d142f3"
metafile = true
