hash-format = "sha256"

[[files]]
file = "datapacks/incendium.pw.toml"
hash = "b68d4abafcd790c6155531cdca3e3a22ff8c07dd6bd8991cad18ea1c28cfb5b5"
metafile = true

[[files]]
file = "datapacks/nullscape.pw.toml"
hash = "636820378f37731932da0051d0f51650291a36afeaff56be8f5c0b0bc746d009"
metafile = true

[[files]]
file = "datapacks/terralith.pw.toml"
hash = "66cc1fa172cf94022bae644237be05b4377ff0686a2745ea9b0a7326c3b08ac6"
metafile = true

[[files]]
file = "datapacks/trek.pw.toml"
hash = "abcb3c3cfe9188552112b4ad35d43014126d623c532f8ae4ae8ea4092b451a6f"
metafile = true

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "fa40e7c9879f4ad59dc466dca96e1f450395568d27c6a6f626047cefda8eaea9"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "6ae37c727d3bfbe006964cc094a7c571c0c516d46b7e26147ffaf984d70cbf72"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "470e949c4f01d769445ff5fd49534ae266bb427c49e16c25b2983299a46825cc"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "e154b918a8b473942f6428fb8f778c08b46befc2f55387dce75ca39164b83b00"
metafile = true

[[files]]
file = "mods/create-connected.pw.toml"
hash = "f87b24365c8a8777a758bc5c9fcc4ead3fd2b29defb7cad617200e3486cb6dc6"
metafile = true

[[files]]
file = "mods/create-diesel-generators.pw.toml"
hash = "02fab017c89f55b1cfbde17d4c9c7945cbd6cac109cc0690a8dda5e4b6ccf44f"
metafile = true

[[files]]
file = "mods/create-dreams-desires.pw.toml"
hash = "25e8878491660347594ab7dc91f3075dcde12f5a20e84952a7a694ac78e4b758"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "36effdfa56cf8aa6d563db77c5dd80b626693d0c77d0b4e3c244aa80c10cab05"
metafile = true

[[files]]
file = "mods/data-anchor.pw.toml"
hash = "7f02ff265c96a103bd044602ab48788520d364c22824a69a77da6f81dd984103"
metafile = true

[[files]]
file = "mods/enhanced-celestials.pw.toml"
hash = "0bb3a092472cc820e42e83ac0aac97e52f8cb2920777b79788bb04dc1da0cebc"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "875e9067e6b573d857ea6524cbf7c9bcaa7a4fc129fe18b422dab88692ddbbaa"
metafile = true

[[files]]
file = "mods/guard-villagers.pw.toml"
hash = "7db4d6f071da73553f0a3d4ca115c89a24effb6c87e15d8f7cebc464239a89c8"
metafile = true

[[files]]
file = "mods/improved-mobs.pw.toml"
hash = "748fda6e06280872a42259eea26312a65d65aa6554d917f44a3658854bda5d39"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "ae86ce95fd8c6d3ff9b924b49beb7a272390ede057348645e6abef726473029e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "e8b121e7dd0d0dc6bee6a968e26c4c2f3cc2372157722bbdced899c62d372860"
metafile = true

[[files]]
file = "mods/prometheus-exporter.pw.toml"
hash = "95b1de582ae2ce9d6e534ea9789ef7915a164648efcd788564aa6609e8deb531"
metafile = true

[[files]]
file = "mods/saturn.pw.toml"
hash = "ddc79fcde38a25173360d928ed69b5cc357aa10b010fc37e0429c426b28d9fcc"
metafile = true

[[files]]
file = "mods/silent-gear.pw.toml"
hash = "fd0fdb1d1acd8b582c5e3ef75877952d7b78f8b6453bb94dba2f68bac60c1017"
metafile = true

[[files]]
file = "mods/silent-lib.pw.toml"
hash = "40ecf884f979abc0c35c9674aa56822eb922ce63dc1ddfd1303076ccab0a434a"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-create-integration.pw.toml"
hash = "df99ef6ffac5c9e897cb39a9cd8549159e43025e01c9168e1ec419bbca695384"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "6b971f27a8ae1ea033d81ebb6369ac2a586f5a80182913f3061a325b077f27ed"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "d145bcd9df3aedbcf414c44b9efde5bd9541ab2316b698bc6d8f1ca3160e9b97"
metafile = true

[[files]]
file = "mods/sophisticated-storage-create-integration.pw.toml"
hash = "0dd277e6d350ac314ed117f1c8cc997da0c2bb05c90ff1c024afc57c515ad948"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "9961f9bd1472ace0c1555ae5669cb4626849028b76d8e4bf065da2f6604830d4"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "11c3d2f6e23cce91ba2b2f1dffc700e9d0e6c8f7406f25bc3b04c93b5bc91b4b"
metafile = true

[[files]]
file = "mods/tenshilib.pw.toml"
hash = "41b9eccff7a35a85444c3aad9a998353c5f720086f43e8c36dc2d3b4a9d142f3"
metafile = true
