hash-format = "sha256"

[[files]]
file = "mods/alltheleaks.pw.toml"
hash = "fa40e7c9879f4ad59dc466dca96e1f450395568d27c6a6f626047cefda8eaea9"
metafile = true

[[files]]
file = "mods/blockui.pw.toml"
hash = "ef6f4494f91c36b089bddbbbc1179e8d0457d5c7d6491900599e36ec18306219"
metafile = true

[[files]]
file = "mods/create-diesel-generators.pw.toml"
hash = "02fab017c89f55b1cfbde17d4c9c7945cbd6cac109cc0690a8dda5e4b6ccf44f"
metafile = true

[[files]]
file = "mods/create-dreams-desires.pw.toml"
hash = "25e8878491660347594ab7dc91f3075dcde12f5a20e84952a7a694ac78e4b758"
metafile = true

[[files]]
file = "mods/create-new-age.pw.toml"
hash = "6a7211cf26561896b195d7890867e25c1079a8717af6b675a68e14ed46b735b0"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "36effdfa56cf8aa6d563db77c5dd80b626693d0c77d0b4e3c244aa80c10cab05"
metafile = true

[[files]]
file = "mods/createcolonies.pw.toml"
hash = "86d92c3ae7a7b8529cffd95499fb7bf68149646ec23f5633a25c218d1c409540"
metafile = true

[[files]]
file = "mods/domum-ornamentum.pw.toml"
hash = "92220e7946172ae3d6995b69dcdc05c8f5b1c29ff8fff24a469e14532c3cb55b"
metafile = true

[[files]]
file = "mods/ferritecore.pw.toml"
hash = "875e9067e6b573d857ea6524cbf7c9bcaa7a4fc129fe18b422dab88692ddbbaa"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "ae86ce95fd8c6d3ff9b924b49beb7a272390ede057348645e6abef726473029e"
metafile = true

[[files]]
file = "mods/minecolonies.pw.toml"
hash = "65eb8f48dfcc1b4b739103acfadea49103669850c7a224672ade635d4134009f"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "e8b121e7dd0d0dc6bee6a968e26c4c2f3cc2372157722bbdced899c62d372860"
metafile = true

[[files]]
file = "mods/multi-piston.pw.toml"
hash = "abcc5a7aedaf2f9f347aea24180a137d85fbd176bb0c76af85b0e84d3f733be0"
metafile = true

[[files]]
file = "mods/prometheus-exporter.pw.toml"
hash = "95b1de582ae2ce9d6e534ea9789ef7915a164648efcd788564aa6609e8deb531"
metafile = true

[[files]]
file = "mods/saturn.pw.toml"
hash = "ddc79fcde38a25173360d928ed69b5cc357aa10b010fc37e0429c426b28d9fcc"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-create-integration.pw.toml"
hash = "df99ef6ffac5c9e897cb39a9cd8549159e43025e01c9168e1ec419bbca695384"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "6b971f27a8ae1ea033d81ebb6369ac2a586f5a80182913f3061a325b077f27ed"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "d145bcd9df3aedbcf414c44b9efde5bd9541ab2316b698bc6d8f1ca3160e9b97"
metafile = true

[[files]]
file = "mods/sophisticated-storage-create-integration.pw.toml"
hash = "0dd277e6d350ac314ed117f1c8cc997da0c2bb05c90ff1c024afc57c515ad948"
metafile = true

[[files]]
file = "mods/sophisticated-storage.pw.toml"
hash = "9961f9bd1472ace0c1555ae5669cb4626849028b76d8e4bf065da2f6604830d4"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "11c3d2f6e23cce91ba2b2f1dffc700e9d0e6c8f7406f25bc3b04c93b5bc91b4b"
metafile = true

[[files]]
file = "mods/structurize.pw.toml"
hash = "8db22beeee61c81a92b180b2dc4c90abdab001574c1b13e5d6b1aa99dda14e56"
metafile = true

[[files]]
file = "mods/towntalk.pw.toml"
hash = "28a573c20c674626ae55f66ab7e972a0fc4c282fd9f8e01516bcb70a3136d36a"
metafile = true
