hash-format = "sha256"

[[files]]
file = "mods/performance/alltheleaks.pw.toml"
hash = "49dedd58a30df8112ca9922789f05726a7775fdc58ef626b05894aad8cfcbea0"
metafile = true

[[files]]
file = "mods/performance/ferritecore.pw.toml"
hash = "942b02525962980b6176677cca162d27c1210b686985ad11db0055fe39d42a7d"
metafile = true

[[files]]
file = "mods/performance/modernfix.pw.toml"
hash = "97521b85e74dfbc642b9102a46be0cdda07b9cfe36aba027a3878054f93ccfcb"
metafile = true

[[files]]
file = "mods/performance/radium-reforged.pw.toml"
hash = "67591382be789035eec313d92c15b224c0bdecab65091c9191c44502a99e834e"
metafile = true

[[files]]
file = "mods/performance/saturn.pw.toml"
hash = "8a0271e7d5c8f4badd2886fd9a8ca75c5a33868ac90828cf3b5dbe932025a0fa"
metafile = true

[[files]]
file = "mods/performance/servercore.pw.toml"
hash = "00f400af981bbe8be3767ef49f4bc422a9649c3fa2d403bae7b25202a05fda1a"
metafile = true

[[files]]
file = "mods/performance/smooth-chunk-save.pw.toml"
hash = "ff6934dbf3203c63dbdab3b2b3a89e82c047ad22db63d8511d737a489aac743c"
metafile = true

[[files]]
file = "mods/performance/spark.pw.toml"
hash = "6d9eaf43c14c66465e87bf03cc5cb5ecef57b3f2e8063c52f6332d33689d30be"
metafile = true
