name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95ca2a88b5685a1d65d110e074d376e1c0de67b874941edadefbfe7d05602264"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
