name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8142a2cb0e77510dc094761e47409ba12e0035c4ccb9bbcc67f6542bb9438664"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
