name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7601b2a91a0307103465013f0c8162916187922fcadd3dfd11127336d46268b7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
