name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f5123b29b43d3dccf09b695d985737f5dad732f3e55f34a09a6d3946ca0a782"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
