name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aa706e7dc0b82f56f43f3de093646a863ddb297f8aeaf6a1ca21cf545b569d9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
