name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e33968075cc5e2caae31e554b587dd03b022cac26df28b5552e265eb37e78c02"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
