name = "Packwiz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a3d93dc965fda2c7cabc41da3975fb6affbf772392f46ae3d5a9a84163320ae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
